# Generated by Django 4.2.2 on 2023-07-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('address1', models.CharField(default='', max_length=100)),
                ('housenumber', models.CharField(default='', max_length=20)),
                ('woreda', models.CharField(default='', max_length=50)),
                ('kebele', models.CharField(default='', max_length=50)),
                ('tell', models.CharField(default='', max_length=20)),
                ('location', models.CharField(default='', max_length=100)),
                ('location1', models.CharField(default='', max_length=100)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('obliged_purchase', models.IntegerField(default=0)),
                ('amount_litter', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('delivery_within', models.IntegerField(default=0)),
                ('valid_year', models.IntegerField(default=0)),
                ('pobox', models.IntegerField(default=0)),
                ('supplierrepre_name', models.CharField(default='', max_length=50)),
                ('supplierrepre_position', models.CharField(default='', max_length=50)),
                ('supplierrepre_signe_date', models.DateField(blank=True, null=True)),
                ('buyerrepre_name', models.CharField(default='', max_length=50)),
                ('buyerrepre_position', models.CharField(default='', max_length=50)),
                ('buyerrepre_signe_date', models.DateField(blank=True, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('wname', models.CharField(default='', max_length=100)),
                ('waddress', models.CharField(default='', max_length=50)),
                ('waddress1', models.CharField(default='', max_length=50)),
                ('wname1', models.CharField(default='', max_length=100)),
                ('suppliercname', models.CharField(default='', max_length=100)),
                ('stown', models.CharField(default='', max_length=100)),
                ('ssubcity', models.CharField(default='', max_length=100)),
                ('sworeda', models.CharField(default='', max_length=100)),
                ('stell', models.CharField(default='', max_length=50)),
                ('sfax', models.IntegerField(default=0)),
                ('shouse', models.CharField(default='', max_length=50)),
                ('sroad', models.IntegerField(default=0)),
                ('spobox', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
