# Generated by Django 4.2.2 on 2023-07-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ken', models.DateField(blank=True, null=True)),
                ('sim', models.CharField(default='', max_length=100)),
                ('sim1', models.CharField(default='', max_length=100)),
                ('adrasha', models.CharField(default='', max_length=100)),
                ('kilil', models.CharField(default='', max_length=100)),
                ('zone', models.CharField(default='', max_length=100)),
                ('woreda', models.CharField(default='', max_length=100)),
                ('radrasha', models.CharField(default='', max_length=100)),
                ('wikilna_ken', models.DateField()),
            ],
        ),
    ]
