# Generated by Django 4.2.2 on 2023-08-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='tewekay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deal',
            name='tewekay_position',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deal',
            name='yediler_bet_kutur',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deal',
            name='yediler_kebele',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deal',
            name='yediler_silk_kutr',
            field=models.CharField(default='', max_length=100),
        ),
    ]
