# Generated by Django 4.2.2 on 2023-08-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peroleum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yegezi_sim', models.CharField(default='', max_length=100)),
                ('Addrasha', models.CharField(default='', max_length=100)),
                ('Kilil', models.CharField(default='', max_length=100)),
                ('ketema', models.CharField(default='', max_length=100)),
                ('wereda', models.CharField(default='', max_length=100)),
                ('kifle_letema', models.CharField(default='', max_length=100)),
                ('kebele', models.CharField(default='', max_length=100)),
                ('yebet_kutur', models.CharField(default='', max_length=100)),
                ('silk_kutur', models.IntegerField(default='', max_length=100)),
                ('gibir_meleya_kutur', models.CharField(default='', max_length=100)),
                ('yefabrika_addrasha', models.CharField(default='', max_length=100)),
                ('yewil_len', models.DateField(default='')),
                ('yemakrebya_gize', models.IntegerField(default='', max_length=100)),
                ('ye_litter_bzat', models.CharField(default='', max_length=100)),
                ('post_kutur', models.IntegerField(default='', max_length=100)),
                ('yeakrabiw_tewekay', models.CharField(default='', max_length=100)),
                ('yeakrabiw_tewekay_halafinet', models.CharField(default='', max_length=100)),
                ('yegezi_tewekay', models.CharField(default='', max_length=100)),
                ('yegezi_tewekay_halafinet', models.CharField(default='', max_length=100)),
                ('andegna_misikir_sim', models.CharField(default='', max_length=100)),
                ('andegna_lisikir_adrasha', models.CharField(default='', max_length=100)),
                ('huletegna_misikir_sim', models.CharField(default='', max_length=100)),
                ('huletegna_misikir_adrasha', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
