# Generated by Django 4.2.2 on 2023-07-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0002_delier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delier',
            old_name='wikilna_ken',
            new_name='wil_ken',
        ),
        migrations.AddField(
            model_name='delier',
            name='rissued_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='rnumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='rsim',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='yemiterut',
            field=models.CharField(default='', max_length=100),
        ),
    ]
