# Generated by Django 4.2.2 on 2023-08-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0002_deal_tewekay_deal_tewekay_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='buyerrepre_signe_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_within',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='obliged_purchase',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pobox',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplierrepre_signe_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_year',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='deal',
            name='misikir1_house_no',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='deal',
            name='misikir2_house_no',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='delier',
            name='misikir1_house_no',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='delier',
            name='misikir2_house_no',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
