# Generated by Django 4.2.2 on 2023-08-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0002_peroleum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peroleum',
            name='post_kutur',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='peroleum',
            name='silk_kutur',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='peroleum',
            name='yemakrebya_gize',
            field=models.IntegerField(default=''),
        ),
    ]
