# Generated by Django 4.2.2 on 2023-07-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0003_rename_wikilna_ken_delier_wil_ken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delier',
            name='rissued_date',
            field=models.DateField(),
        ),
    ]
