# Generated by Django 4.2.2 on 2023-08-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0003_alter_peroleum_post_kutur_alter_peroleum_silk_kutur_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peroleum',
            new_name='Petroleum',
        ),
    ]
