# Generated by Django 4.2.2 on 2023-08-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0004_rename_yewil_len_petroleum_yewil_ken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount_litter',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sfax',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sroad',
            field=models.CharField(default='', max_length=100),
        ),
    ]
