# Generated by Django 4.2.2 on 2023-08-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0004_rename_peroleum_petroleum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petroleum',
            name='silk_kutur',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='yemakrebya_gize',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='yewil_len',
            field=models.CharField(default=''),
        ),
    ]
