# Generated by Django 4.2.2 on 2023-07-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0004_alter_delier_rissued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='delier',
            name='ke_yetesete',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='madya_area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='madya_ketema',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='delier',
            name='madya_kilil',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='delier',
            name='map_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delier',
            name='map_kutr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='temezgbo_yemigegn',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='delier',
            name='rissued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delier',
            name='wil_ken',
            field=models.DateField(blank=True, null=True),
        ),
    ]
