# Generated by Django 4.2.2 on 2023-07-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0005_delier_ke_yetesete_delier_madya_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delier',
            name='misikir1_house_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delier',
            name='misikir2_house_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delier',
            name='miskir1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='miskir2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
