# Generated by Django 4.2.2 on 2023-09-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0005_alter_contract_amount_litter_alter_contract_sfax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=20)),
                ('Adrasha', models.CharField(max_length=40)),
                ('ketema', models.CharField(max_length=40)),
                ('kifle_ketema', models.CharField(max_length=40)),
                ('wereda', models.CharField(max_length=40)),
                ('yebet_kutr', models.CharField(max_length=40)),
                ('silk_kutr', models.CharField(max_length=40)),
                ('date_year', models.CharField(max_length=40)),
            ],
        ),
    ]
