# Generated by Django 4.2.2 on 2023-09-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0006_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='contract_length',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='misikir1_address',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='misikir1_house_no',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='misikir2_address',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='misikir2_house_no',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='miskir1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='miskir2',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='numberof_cars',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='transport',
            name='transporter_tewekay',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='transporter_tewekay_position',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='waddress',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='waddress1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='wil_ken',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='wname',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='wname1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='yekubanya_tewekay',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='yekubanya_tewekay_position',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='yekubanya_title',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transport',
            name='yeseleda_kutr',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='transport',
            name='yeseleda_kutr1',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='transport',
            name='yeseleda_kutr2',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='transport',
            name='yeseleda_kutr3',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='transport',
            name='yetesabi_kutr',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='transport',
            name='yetesabi_kutr1',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='transport',
            name='yetesabi_kutr2',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='transport',
            name='yetesabi_kutr3',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='transport',
            name='Adrasha',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='transport',
            name='date_year',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='transport',
            name='ketema',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='transport',
            name='kifle_ketema',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='transport',
            name='silk_kutr',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='transport',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transporter_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='transport',
            name='wereda',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='transport',
            name='yebet_kutr',
            field=models.CharField(default='', max_length=40),
        ),
    ]
