# Generated by Django 4.2.2 on 2023-07-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0006_delier_misikir1_house_no_delier_misikir2_house_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delier',
            name='delier_tewekay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='kubanya_position',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='kubanya_tewekay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='misikir1_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='misilir2_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='tewekay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='tewkay_position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
