# Generated by Django 4.2.2 on 2023-09-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0007_transport_contract_length_transport_misikir1_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='print_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
