# Generated by Django 4.2.2 on 2023-07-31 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0007_delier_delier_tewekay_delier_kubanya_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delier',
            old_name='tewkay_position',
            new_name='tewekay_position',
        ),
    ]
