# Generated by Django 4.2.2 on 2023-08-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0008_rename_tewkay_position_delier_tewekay_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delier',
            old_name='sim1',
            new_name='yediler_bet_kutur',
        ),
        migrations.RenameField(
            model_name='delier',
            old_name='yemiterut',
            new_name='yediler_kebele',
        ),
    ]
