# Generated by Django 4.2.2 on 2023-08-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0009_rename_sim1_delier_yediler_bet_kutur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delier',
            name='yediler_silk_kutr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='yediler_tewekay_kebele',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='yediler_tewekay_silk_kutr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delier',
            name='yedilier_tewekay_bet_kutr',
            field=models.CharField(default='', max_length=100),
        ),
    ]
