# Generated by Django 4.2.2 on 2023-08-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0011_delier_madya_wereda_delier_madya_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delier',
            name='ke_yetesete',
            field=models.CharField(default='', max_length=500),
        ),
    ]
