# Generated by Django 4.2.2 on 2023-08-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0013_alter_delier_rissued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delier',
            name='map_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
