# Generated by Django 4.2.2 on 2023-08-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haile', '0015_alter_delier_ken_alter_delier_wil_ken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ken', models.CharField(default='', max_length=100)),
                ('sim', models.CharField(default='', max_length=100)),
                ('madya_zone', models.CharField(default='', max_length=100)),
                ('madya_wereda', models.CharField(default='', max_length=100)),
                ('adrasha', models.CharField(default='', max_length=100)),
                ('kilil', models.CharField(default='', max_length=100)),
                ('zone', models.CharField(default='', max_length=100)),
                ('woreda', models.CharField(default='', max_length=100)),
                ('wil_ken', models.CharField(default='', max_length=100)),
                ('madya_kilil', models.CharField(default='', max_length=50)),
                ('madya_ketema', models.CharField(default='', max_length=50)),
                ('madya_area', models.CharField(default='', max_length=100)),
                ('map_kutr', models.CharField(default='', max_length=100)),
                ('map_date', models.CharField(default='', max_length=100)),
                ('ke_yetesete', models.CharField(default='', max_length=500)),
                ('temezgbo_yemigegn', models.CharField(default='', max_length=100)),
                ('misikir1_house_no', models.IntegerField(default=0)),
                ('misikir2_house_no', models.IntegerField(default=0)),
                ('miskir1', models.CharField(default='', max_length=100)),
                ('miskir2', models.CharField(default='', max_length=100)),
                ('misikir1_address', models.CharField(default='', max_length=100)),
                ('misilir2_address', models.CharField(default='', max_length=100)),
                ('kubanya_tewekay', models.CharField(default='', max_length=100)),
                ('kubanya_position', models.CharField(default='', max_length=100)),
                ('delier_tewekay', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
